language: python
sudo: false
python:
 - "2.6"
 - "2.7"
 - "3.3"
 - "3.4"
 - "3.5"
 - "pypy"
 - "pypy3"
matrix:
  include:
   - python: "pypy"
     env: PERFT=1
addons:
  apt:
    packages:
     - liblzma-dev
cache:
  directories:
    - data/gaviota
before_install:
 - # Stockfish
 - wget https://stockfish.s3.amazonaws.com/stockfish-6-linux.zip
 - unzip stockfish-6-linux.zip
 - mkdir -p bin
 - cp stockfish-6-linux/Linux/stockfish_6_x64 bin/stockfish
 - export PATH="`pwd`/bin:${PATH}"
 - which stockfish || (echo $PATH && false)
 - # Gaviota libgtb
 - git clone https://github.com/michiguel/Gaviota-Tablebases.git --depth 1
 - cd Gaviota-Tablebases
 - make
 - export LD_LIBRARY_PATH="`pwd`:${LD_LIBRARY_PATH}"
 - cd ..
 - # Gaviota tablebases
 - cd data/gaviota
 - wget --no-check-certificate --no-clobber --input-file TEST-SOURCE.txt
 - cd ../..
install:
 - pip install coverage coveralls
script:
 - if [[ $PERFT -ne 1 ]]; then coverage erase; fi
 - if [[ $PERFT -ne 1 ]]; then coverage run --source chess setup.py test --verbose; fi
 - if [[ $PERFT -ne 1 ]]; then coveralls || [[ $? -eq 139 ]]; fi
 - if [[ $PERFT -eq 1 ]]; then python perft.py --verbose; fi
